### ISSUE TITLE
在播放的时候，，切出去，再进正在播放会卡一下

### ISSUE THREAD

**Issue by xiao-ben** [lvpangpang/cloud-music#5]
这个能解决吗？

**Comment by lvpangpang** [comment]
这个 被你发现了 说明你很细心哈
这个是我一开始就弄错了 应该把play.vue组件放app.vue就和search.vue一样，这样才能完美实现后台播放
我现在是点击正在播放然后会再次请求资源 所以卡顿的时候就是请求的时候，当然当前歌曲的播放进度我是存vuex里面的。
谢谢建议哈

**Comment by lvpangpang** [comment]
这个我会改的哈 改好通知你哈

**Comment by lvpangpang** [comment]
改好了  你可以下载看看哈
